openapi: 3.0.0
info:
  title: File Upload API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /upload:
    post:
      summary: Upload a file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
  /merge:
    get:
      summary: Merge files
      responses:
        '200':
          description: Files merged successfully
        '500':
          description: Error merging files
  /read:
    get:
      summary: Read the latest merged file
      responses:
        '200':
          description: Merged file content
        '404':
          description: No merged files found
        '500':
          description: Error reading merged file
